Repository WildCodeSchool-2024-09/js-toulouse-geocode, pull requests merged in 2025-01, with the labels that each got.

#1 feat: create whole tables for geocode database
  server/database/schema.sql
Labels: REVIEWD

#2 feat: create all welcome page components
  client/public/images/get-started-map.png
  client/public/images/logo-welcome-screen.svg
  client/public/images/right-arrow.svg
  client/public/vite.svg
  client/src/App.css
  client/src/components/FirstWelcomeScreen.tsx
  client/src/components/GetStartedScreen.tsx
  client/src/components/SecondWelcomeScreen.tsx
  client/src/main.tsx
Labels: REVIEWD

#3 implement menu bar and links.
  client/public/images/contact.svg
  client/public/images/home.svg
  client/public/images/map.svg
  client/public/images/user.svg
  client/src/App.css
  client/src/App.tsx
  client/src/components/MenuBar.tsx
  client/src/components/SecondWelcomeScreen.tsx
  client/src/main.tsx
  client/src/pages/ContactPage.tsx
  client/src/pages/GeoMapPage.tsx
  client/src/pages/UserPage.tsx
  client/src/styles/MenuBar.css
Labels: REVIEWD

#4 Implement page containing map components et city search
  client/package.json
  client/src/App.tsx
  client/src/components/QueryCity.tsx
  client/src/contexts/GeoPositionContextProvider.tsx
  client/src/pages/GeoMapPage.tsx
  client/src/styles/GeoMap.css
  client/src/types/GeoCoords.ts
  package-lock.json
Labels: REVIEWD

#5 add css to map page
  client/src/components/QueryCity.tsx
  client/src/styles/GeoMap.css
Labels: REVIEWD

#6 add frames for station information
  client/public/images/arrow-collapse.svg
  client/src/App.css
  client/src/components/DisplayStation.tsx
  client/src/components/StationMain.tsx
  client/src/components/StationTitle.tsx
  client/src/pages/GeoMapPage.tsx
  client/src/styles/DisplayStation.css
  client/src/styles/GeoMap.css
  client/src/styles/MenuBar.css
Labels: REVIEWD

#8 Change type of access_charging, type, add address
  server/database/schema.sql
Labels: REVIEWD

#10 style: fix responsive problems
  client/public/images/get-started-map.png
  client/src/components/GetStartedScreen.tsx
  client/src/styles/GetStartedScreen.css
  client/src/styles/SecondWelcomeScreen.css
Labels: REVIEWD

#12 feat: create profil main page
  client/public/images/delete.svg
  client/public/images/empty-profile-photo.png
  client/public/images/modify.svg
  client/src/components/ArticlePersonalInfo.tsx
  client/src/components/ProfileInfo.tsx
  client/src/components/ProfileNavbar.tsx
  client/src/components/ProfilePhoto.tsx
  client/src/pages/UserPage.tsx
  client/src/styles/FirstWelcomeScreen.css
  client/src/styles/GetStartedScreen.css
  client/src/styles/SecondWelcomeScreen.css
Labels: REVIEWD

#13 S1 us28/connexion admin page
  client/public/images/arrow-admin-img.svg
  client/public/images/geocode-logo.svg
  client/public/images/logout-admin-img.svg
  client/public/images/station-admin-img.svg
  client/public/images/update-admin-img.svg
  client/public/images/user-admin-img.svg
  client/public/images/vehicle-admin-img.svg
  client/src/App.css
  client/src/admin/AppAdmin.css
  client/src/admin/AppAdmin.tsx
  client/src/admin/assets/.gitkeep
  client/src/admin/assets/images/.gitkeep
  client/src/admin/components/.gitkeep
  client/src/admin/components/FormConnexionAdmin.tsx
  client/src/admin/components/HeaderAdminPage.tsx
  client/src/admin/components/NavAdmin.tsx
  client/src/admin/contexts/.gitkeep
  client/src/admin/pages/.gitkeep
  client/src/admin/pages/ConnexionAdminPage.tsx
  client/src/admin/pages/UsersPage.tsx
  client/src/admin/services/.gitkeep
  client/src/admin/styles/.gitkeep
  client/src/admin/types/.gitkeep
  client/src/main.tsx
  client/src/styles/FirstWelcomeScreen.css
  client/src/styles/GetStartedScreen.css
  client/src/styles/SecondWelcomeScreen.css
  server/src/modules/insertData/insertDataAction.ts
  server/src/router.ts
Labels: REVIEWD

#14 fetch data from server for all stations in map
  client/public/images/marker.png
  client/public/images/marker.svg
  client/src/App.tsx
  client/src/components/FirstWelcomeScreen.tsx
  client/src/components/MenuBar.tsx
  client/src/components/QueryCity.tsx
  client/src/components/StationMarker.tsx
  client/src/contexts/StationsLocationsContextProvider.tsx
  client/src/main.tsx
  client/src/pages/ContactPage.tsx
  client/src/pages/GeoMapPage.tsx
  client/src/pages/UserPage.tsx
  server/bin/services/csvManagement.ts
  server/common/types/StationProps.ts
  server/src/modules/insertData/insertDataRepository.ts
  server/src/modules/station/stationActions.ts
  server/src/modules/station/stationRepository.ts
  server/src/router.ts
  server/types/csvDataType.d.ts
Labels: CONFLICTS, REVIEWD

#15 freeze issues on map and load of Geocode logo
  client/src/components/FirstWelcomeScreen.tsx
  client/src/main.tsx
  server/src/modules/station/stationRepository.ts
Labels: REVIEWD

#17 fill station info tag with data from station
  client/public/images/address.svg
  client/src/components/StationMain.tsx
  client/src/components/StationMarker.tsx
  client/src/components/StationTitle.tsx
  client/src/contexts/StationsLocationsContextProvider.tsx
  client/src/pages/GeoMapPage.tsx
  client/src/styles/DisplayStation.css
  server/common/types/StationProps.ts
  server/src/modules/station/stationActions.ts
  server/src/modules/station/stationRepository.ts
  server/src/router.ts
Labels: REVIEWD

#18 style: add style to connection page
  client/package.json
  client/src/admin/components/ContentAdmin.tsx
  client/src/admin/components/FormConnexionAdmin.tsx
  client/src/admin/components/HeaderAdminPage.tsx
  client/src/admin/components/NavAdmin.tsx
  client/src/admin/pages/ConnectionAdminPage.tsx
  client/src/admin/pages/UsersPage.tsx
  client/src/admin/styles/ConnectionAdminPage.css
  client/src/admin/styles/ContentAdmin.css
  client/src/admin/styles/FormConnexionAdmin.css
  client/src/admin/styles/HeaderAdminPage.css
  client/src/admin/styles/NavAdmin.css
  client/src/admin/styles/UsersPage.css
  client/src/main.tsx
  package-lock.json
Labels: REVIEWD

#19 add components to contact page
  client/src/components/ContactForm.tsx
  client/src/pages/ContactPage.tsx
Labels: REVIEWD

#20 S2 us44/charging station admin page
  client/src/admin/components/NavAdmin.tsx
  client/src/admin/pages/StationPage.tsx
  client/src/admin/styles/FormConnexionAdmin.css
  client/src/admin/styles/StationPage.css
  client/src/main.tsx
Labels: REVIEWD

#22 add style to context page
  client/src/pages/ContactPage.tsx
  client/src/styles/ContactPage.css
  client/src/styles/DisplayStation.css
Labels: REVIEWD

#23 send contact information to server database
  client/src/components/ContactForm.tsx
  server/database/schema.sql
  server/src/app.ts
  server/src/modules/contact/contactActions.ts
  server/src/modules/contact/contactRepository.ts
  server/src/router.ts
Labels: REVIEWD

#24 S2 us56/profile page upload photo
  client/src/components/ConfirmationDeletePhoto.tsx
  client/src/components/ProfileInfo.tsx
  client/src/components/ProfilePhoto.tsx
  client/src/main.tsx
  client/src/pages/UserPage.tsx
  client/src/styles/ConfirmationDeletePhoto.css
  client/src/styles/ConfirmationUploadPhoto.css
  package-lock.json
  server/database/schema.sql
  server/package.json
  server/src/modules/modifyPhoto/modifyPhotoActions.ts
  server/src/modules/userPhoto/userPhotoActions.ts
  server/src/modules/userPhoto/userPhotoRepository.ts
  server/src/router.ts
Labels: REVIEWD

#26 feat: create vehicles list page
  client/src/components/VehiclesInfosCard.tsx
  client/src/components/VehiclesInfosList.tsx
  client/src/pages/UserPage.tsx
Labels: REVIEWD

#27 add style to reservation component
  client/src/components/StationReservation.tsx
  client/src/styles/DisplayStation.css
Labels: REVIEWD

#29 fix: correct responsiveness, flex display
  client/src/App.css
  client/src/components/DisplayStation.tsx
  client/src/components/MenuBar.tsx
  client/src/components/StationTitle.tsx
  client/src/styles/DisplayStation.css
  client/src/styles/MenuBar.css
Labels: REVIEWD

#30 style: finish styling vehicles page
  client/src/App.css
  client/src/components/VehiclesInfosCard.tsx
  client/src/components/VehiclesInfosList.tsx
  client/src/styles/ConfirmationUploadPhoto.css
  client/src/styles/FirstWelcomeScreen.css
  client/src/styles/GetStartedScreen.css
  client/src/styles/ProfileInfo.css
  client/src/styles/ProfileNavbar.css
  client/src/styles/SecondWelcomeScreen.css
  client/src/styles/VehiclesInfosCard.css
  client/src/styles/VehiclesInfosList.css
Labels: REVIEWD

#31 fix: fix responsive bugs on some buttons
  client/src/styles/ConfirmationUploadPhoto.css
  client/src/styles/ProfileInfo.css
  client/src/styles/VehiclesInfosList.css
Labels: REVIEWD

#32 feat: create booking page with components and style
  client/src/App.css
  client/src/components/BookingsInfos.tsx
  client/src/components/BookingsInfosCard.tsx
  client/src/pages/UserPage.tsx
  client/src/styles/BookingsInfos.css
  client/src/styles/BookingsInfosCard.css
  client/src/styles/ProfileInfo.css
  client/src/styles/ProfileNavbar.css
  client/src/styles/ProfilePhoto.css
  client/src/styles/VehiclesInfosCard.css
  client/src/styles/VehiclesInfosList.css
Labels: REVIEWD

#33 implement register page
  client/src/components/RegisterForm.tsx
  client/src/main.tsx
  client/src/pages/RegisterPage.tsx
  client/src/styles/RegisterPage.css
Labels: REVIEWD

#34 implement css for register page
  client/src/components/RegisterForm.tsx
  client/src/styles/ContactPage.css
  client/src/styles/RegisterPage.css
Labels: REVIEWD

#35 feat: create login page
  client/src/components/LoginForm.tsx
  client/src/main.tsx
  client/src/pages/LoginPage.tsx
Labels: REVIEWD

#37 S3 us14/style connection page
  client/src/components/LoginForm.tsx
  client/src/pages/LoginPage.tsx
  client/src/styles/LoginPage.css
Labels: REVIEWD

#39 feat: implement fetch during login
  client/src/App.tsx
  client/src/components/LoginForm.tsx
  client/src/components/MenuBar.tsx
  client/src/contexts/AuthProvider.tsx
  client/src/contexts/GlobalContext.tsx
  client/src/main.tsx
  client/src/styles/LoginPage.css
  package-lock.json
  server/database/schema.sql
  server/package.json
  server/src/modules/auth/authActions.ts
  server/src/modules/user/userRepository.ts
  server/src/router.ts
  server/types/express/index.d.ts
Labels: REVIEWD

#41 replace button 'Réserver' by 'Se connecter' if not connected
  client/src/components/StationDescription.tsx
  client/src/styles/ContactPage.css
  client/src/styles/RegisterPage.css
Labels: REVIEWD

#42 introduce insee code for cities and correct fill of database
  server/bin/services/csvManagement.ts
  server/database/schema.sql
  server/src/modules/insertData/insertDataRepository.ts
  server/src/modules/station/stationRepository.ts
  server/src/modules/user/userRepository.ts
Labels: REVIEWD

#44 put the right insee code in user table
  server/src/modules/user/userActions.ts
  server/src/modules/user/userRepository.ts
Labels: REVIEWD

#45 implement component user modification
  client/public/images/close.svg
  client/src/admin/components/UserModification.tsx
  client/src/admin/pages/UsersPage.tsx
Labels: REVIEWD

#47 add style to user modifications component
  client/src/App.css
  client/src/admin/components/UserModification.tsx
  client/src/admin/styles/UsersPage.css
Labels: REVIEWD

#48 S3 us18/modify infos user
  client/src/components/ModifyProfileInfos.tsx
  client/src/components/ProfileInfo.tsx
  client/src/components/ProfilePhoto.tsx
  client/src/styles/ModifyProfileInfos.css
  client/src/styles/ProfilePhoto.css
  server/src/modules/city/cityActions.ts
  server/src/modules/city/cityRepository.ts
  server/src/modules/codeInsee/codeInseeActions.ts
  server/src/modules/codeInsee/codeInseeRepository.ts
  server/src/modules/department/departementActions.ts
  server/src/modules/department/departementRepository.ts
  server/src/modules/insertData/insertDataRepository.ts
  server/src/modules/postalCode/postalcodeActions.ts
  server/src/modules/postalCode/postalcodeRepository.ts
  server/src/modules/user/userActions.ts
  server/src/modules/user/userRepository.ts
  server/src/modules/userPhoto/userPhotoActions.ts
  server/src/router.ts
Labels: REVIEWD

#49 feat: create search bar
  client/src/admin/components/ContentAdmin.tsx
  client/src/admin/styles/ContentAdmin.css
  client/src/admin/styles/StationItemAdmin.css
  server/src/modules/station/stationActions.ts
  server/src/modules/station/stationRepository.ts
  server/src/router.ts
Labels: REVIEWD

#50 S3 us32/show user in user page
  client/src/admin/components/StationItemAdmin.tsx
  client/src/admin/components/UserItemAdmin.tsx
  client/src/admin/components/UserModification.tsx
  client/src/admin/contexts/ShowModifyModalProvider.tsx
  client/src/admin/pages/UsersPage.tsx
  client/src/admin/styles/UserItemAdmin.css
  client/src/admin/types/itemType.ts
  client/src/components/ProfileInfo.tsx
  client/src/contexts/GlobalContext.tsx
  server/src/modules/codeInsee/codeInseeActions.ts
  server/src/modules/codeInsee/codeInseeRepository.ts
  server/src/modules/station/stationRepository.ts
  server/src/modules/user/userActions.ts
  server/src/modules/user/userRepository.ts
  server/src/router.ts
Labels: CORRECTIONS_DONE, REVIEWD

#51 S4 us61/confirm delete profile component
  client/src/components/ConfirmationDeleteProfile.tsx
  client/src/components/ModifyProfileInfos.tsx
  client/src/components/ProfileInfo.tsx
  client/src/styles/ConfirmationDeletePhoto.css
  client/src/styles/ModifyProfileInfos.css
Labels: REVIEWD

#53 feat: enable profile deletion in database
  client/src/components/ConfirmationDeleteProfile.tsx
  server/src/modules/user/userActions.ts
  server/src/modules/user/userRepository.ts
  server/src/router.ts
Labels: CORRECTIONS_DONE

#54 send user infos to backend
  client/src/admin/components/UserItemAdmin.tsx
  client/src/admin/components/UserModification.tsx
  client/src/admin/contexts/ShowModifyModalProvider.tsx
  client/src/admin/pages/UsersPage.tsx
  client/src/components/MenuBar.tsx
  client/src/components/ModifyProfileInfos.tsx
  client/src/components/ProfileInfo.tsx
  client/src/components/RegisterForm.tsx
  server/src/modules/auth/authActions.ts
  server/src/modules/user/userActions.ts
  server/src/modules/user/userRepository.ts
  server/src/router.ts
Labels: REVIEWD

#56 feat: delete user in user page
  client/src/App.css
  client/src/admin/components/UserDeleteModal.tsx
  client/src/admin/components/UserItemAdmin.tsx
  client/src/admin/components/UserModification.tsx
  client/src/admin/contexts/ShowModalProvider.tsx
  client/src/admin/contexts/ShowModifyModalProvider.tsx
  client/src/admin/pages/UsersPage.tsx
  client/src/admin/styles/UserDeleteModal.css
  client/src/contexts/GlobalContext.tsx
  server/database/schema.sql
  server/src/modules/user/userActions.ts
  server/src/modules/user/userRepository.ts
  server/src/router.ts
Labels: REVIEWD

#57 style: add style to delete user modal
  client/src/App.css
  client/src/admin/components/ContentAdmin.tsx
  client/src/admin/components/DeleteModal.tsx
  client/src/admin/contexts/ShowModalProvider.tsx
  client/src/admin/pages/UsersPage.tsx
  client/src/admin/styles/UserDeleteModal.css
Labels: REVIEWD

#55 S4 us64/add vehicle component
  client/src/components/AddUserVehicle.tsx
  client/src/components/ProfileNavbar.tsx
  client/src/components/VehiclesInfosList.tsx
  server/src/modules/user/userActions.ts
  server/src/modules/vehicle/vehicleRepository.ts
Labels: REVIEWD

#58 S4 us43/delete vehicle in vehicle page
  client/src/admin/components/DeleteModal.tsx
  client/src/admin/components/VehicleItemAdmin.tsx
  client/src/admin/pages/UsersPage.tsx
  client/src/admin/pages/VehiclePage.tsx
  client/src/admin/styles/VehicleItemAdmin.css
  server/src/modules/vehicle/vehicleActions.ts
  server/src/modules/vehicle/vehicleRepository.ts
  server/src/router.ts
Labels: REVIEWD

#60 S4 us49/delete station in station page
  client/src/admin/components/DeleteModal.tsx
  client/src/admin/components/StationItemAdmin.tsx
  client/src/admin/components/UserItemAdmin.tsx
  client/src/admin/components/VehicleItemAdmin.tsx
  client/src/admin/contexts/ShowModalProvider.tsx
  client/src/admin/pages/StationPage.tsx
  client/src/admin/pages/UsersPage.tsx
  client/src/admin/pages/VehiclePage.tsx
  client/src/admin/styles/StationItemAdmin.css
  client/src/admin/styles/UserItemAdmin.css
  server/src/modules/station/stationActions.ts
  server/src/modules/station/stationRepository.ts
  server/src/router.ts
Labels: REVIEWD

#62 style: add styles to add vehicle component
  client/src/components/AddUserVehicle.tsx
  client/src/styles/AddUserVehicle.css
Labels: REVIEWD

#63 implement station query and update
  client/src/admin/components/StationModification.tsx
  client/src/admin/styles/StationPage.css
  server/src/modules/insertData/insertDataRepository.ts
  server/src/modules/station/stationActions.ts
  server/src/modules/station/stationRepository.ts
  server/src/router.ts
Labels: REVIEWD

#64 feat: make vehicle adding effective in database
  client/src/components/AddUserVehicle.tsx
  server/src/modules/insertData/insertDataAction.ts
  server/src/modules/vehicle/vehicleActions.ts
  server/src/modules/vehicle/vehicleRepository.ts
  server/src/router.ts
Labels: REVIEWD

#65 implement vehicle modification component
  client/src/admin/components/UserItemAdmin.tsx
  client/src/admin/components/VehicleItemAdmin.tsx
  client/src/admin/components/VehicleModification.tsx
  client/src/admin/pages/UsersPage.tsx
  client/src/admin/pages/VehiclePage.tsx
Labels: REVIEWD

#67 add style to vehicle modification component
  client/src/admin/pages/VehiclePage.tsx
  client/src/admin/styles/VehiclePage.css
Labels: REVIEWD

#68 fix: resolve bug before implementing admin connection feature
  client/src/admin/components/ContentAdmin.tsx
  client/src/admin/components/DeleteModal.tsx
  client/src/admin/components/StationItemAdmin.tsx
  client/src/admin/components/UserItemAdmin.tsx
  client/src/admin/components/UserModification.tsx
  client/src/admin/components/VehicleItemAdmin.tsx
Labels: REVIEWD

#69 S4 us66/make vehicle add effective in database
  client/src/components/AddUserVehicle.tsx
  client/src/components/ProfileNavbar.tsx
  client/src/pages/UserPage.tsx
  server/src/modules/user/userRepository.ts
  server/src/modules/vehicle/vehicleActions.ts
Labels: REVIEWD

#70 implement vehicle query and update
  client/src/admin/components/StationModification.tsx
  client/src/admin/components/UserModification.tsx
  client/src/admin/components/VehicleModification.tsx
  server/src/modules/vehicle/vehicleActions.ts
  server/src/modules/vehicle/vehicleRepository.ts
  server/src/router.ts
Labels: REVIEWD

#71 S4 us67/admin connection
  client/src/admin/components/ContentAdmin.tsx
  client/src/admin/components/FormConnexionAdmin.tsx
  client/src/admin/contexts/ShowNavProvider.tsx
  client/src/pages/UserPage.tsx
  server/database/schema.sql
  server/src/modules/auth/authActions.ts
  server/src/modules/user/userRepository.ts
  server/src/router.ts
Labels: REVIEWD

#72 feat: fetch user vehicles from database
  client/src/components/AddUserVehicle.tsx
  client/src/components/VehiclesInfosList.tsx
  client/src/pages/UserPage.tsx
  server/src/modules/vehicle/vehicleActions.ts
  server/src/modules/vehicle/vehicleRepository.ts
  server/src/router.ts
Labels: REVIEWD

#73 do not include falsy values for cities, departments and regions in database
  server/src/modules/insertData/insertDataRepository.ts
Labels: REVIEWD

#74 fix: corrige fetch vehicles
  client/src/components/VehiclesInfosList.tsx
  server/database/schema.sql
Labels: REVIEWD
